// +build !ignore_autogenerated

/*
Copyright 2019 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apisv1alpha1 "github.com/crossplane/provider-rook/apis/v1alpha1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CockroachCluster) DeepCopyInto(out *CockroachCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CockroachCluster.
func (in *CockroachCluster) DeepCopy() *CockroachCluster {
	if in == nil {
		return nil
	}
	out := new(CockroachCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CockroachCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CockroachClusterClass) DeepCopyInto(out *CockroachClusterClass) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.SpecTemplate.DeepCopyInto(&out.SpecTemplate)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CockroachClusterClass.
func (in *CockroachClusterClass) DeepCopy() *CockroachClusterClass {
	if in == nil {
		return nil
	}
	out := new(CockroachClusterClass)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CockroachClusterClass) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CockroachClusterClassList) DeepCopyInto(out *CockroachClusterClassList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CockroachClusterClass, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CockroachClusterClassList.
func (in *CockroachClusterClassList) DeepCopy() *CockroachClusterClassList {
	if in == nil {
		return nil
	}
	out := new(CockroachClusterClassList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CockroachClusterClassList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CockroachClusterClassSpecTemplate) DeepCopyInto(out *CockroachClusterClassSpecTemplate) {
	*out = *in
	out.ClassSpecTemplate = in.ClassSpecTemplate
	in.CockroachClusterParameters.DeepCopyInto(&out.CockroachClusterParameters)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CockroachClusterClassSpecTemplate.
func (in *CockroachClusterClassSpecTemplate) DeepCopy() *CockroachClusterClassSpecTemplate {
	if in == nil {
		return nil
	}
	out := new(CockroachClusterClassSpecTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CockroachClusterList) DeepCopyInto(out *CockroachClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CockroachCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CockroachClusterList.
func (in *CockroachClusterList) DeepCopy() *CockroachClusterList {
	if in == nil {
		return nil
	}
	out := new(CockroachClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CockroachClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CockroachClusterParameters) DeepCopyInto(out *CockroachClusterParameters) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(apisv1alpha1.Annotations, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.Storage.DeepCopyInto(&out.Storage)
	in.Network.DeepCopyInto(&out.Network)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CockroachClusterParameters.
func (in *CockroachClusterParameters) DeepCopy() *CockroachClusterParameters {
	if in == nil {
		return nil
	}
	out := new(CockroachClusterParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CockroachClusterSpec) DeepCopyInto(out *CockroachClusterSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.CockroachClusterParameters.DeepCopyInto(&out.CockroachClusterParameters)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CockroachClusterSpec.
func (in *CockroachClusterSpec) DeepCopy() *CockroachClusterSpec {
	if in == nil {
		return nil
	}
	out := new(CockroachClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CockroachClusterStatus) DeepCopyInto(out *CockroachClusterStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CockroachClusterStatus.
func (in *CockroachClusterStatus) DeepCopy() *CockroachClusterStatus {
	if in == nil {
		return nil
	}
	out := new(CockroachClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkSpec) DeepCopyInto(out *NetworkSpec) {
	*out = *in
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]PortSpec, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkSpec.
func (in *NetworkSpec) DeepCopy() *NetworkSpec {
	if in == nil {
		return nil
	}
	out := new(NetworkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PortSpec) DeepCopyInto(out *PortSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PortSpec.
func (in *PortSpec) DeepCopy() *PortSpec {
	if in == nil {
		return nil
	}
	out := new(PortSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServerSpec) DeepCopyInto(out *ServerSpec) {
	*out = *in
	in.Network.DeepCopyInto(&out.Network)
	in.VolumeClaimTemplate.DeepCopyInto(&out.VolumeClaimTemplate)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServerSpec.
func (in *ServerSpec) DeepCopy() *ServerSpec {
	if in == nil {
		return nil
	}
	out := new(ServerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *YugabyteCluster) DeepCopyInto(out *YugabyteCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new YugabyteCluster.
func (in *YugabyteCluster) DeepCopy() *YugabyteCluster {
	if in == nil {
		return nil
	}
	out := new(YugabyteCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *YugabyteCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *YugabyteClusterClass) DeepCopyInto(out *YugabyteClusterClass) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.SpecTemplate.DeepCopyInto(&out.SpecTemplate)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new YugabyteClusterClass.
func (in *YugabyteClusterClass) DeepCopy() *YugabyteClusterClass {
	if in == nil {
		return nil
	}
	out := new(YugabyteClusterClass)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *YugabyteClusterClass) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *YugabyteClusterClassList) DeepCopyInto(out *YugabyteClusterClassList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]YugabyteClusterClass, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new YugabyteClusterClassList.
func (in *YugabyteClusterClassList) DeepCopy() *YugabyteClusterClassList {
	if in == nil {
		return nil
	}
	out := new(YugabyteClusterClassList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *YugabyteClusterClassList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *YugabyteClusterClassSpecTemplate) DeepCopyInto(out *YugabyteClusterClassSpecTemplate) {
	*out = *in
	out.ClassSpecTemplate = in.ClassSpecTemplate
	in.YugabyteClusterParameters.DeepCopyInto(&out.YugabyteClusterParameters)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new YugabyteClusterClassSpecTemplate.
func (in *YugabyteClusterClassSpecTemplate) DeepCopy() *YugabyteClusterClassSpecTemplate {
	if in == nil {
		return nil
	}
	out := new(YugabyteClusterClassSpecTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *YugabyteClusterList) DeepCopyInto(out *YugabyteClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]YugabyteCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new YugabyteClusterList.
func (in *YugabyteClusterList) DeepCopy() *YugabyteClusterList {
	if in == nil {
		return nil
	}
	out := new(YugabyteClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *YugabyteClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *YugabyteClusterParameters) DeepCopyInto(out *YugabyteClusterParameters) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(apisv1alpha1.Annotations, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.Master.DeepCopyInto(&out.Master)
	in.TServer.DeepCopyInto(&out.TServer)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new YugabyteClusterParameters.
func (in *YugabyteClusterParameters) DeepCopy() *YugabyteClusterParameters {
	if in == nil {
		return nil
	}
	out := new(YugabyteClusterParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *YugabyteClusterSpec) DeepCopyInto(out *YugabyteClusterSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.YugabyteClusterParameters.DeepCopyInto(&out.YugabyteClusterParameters)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new YugabyteClusterSpec.
func (in *YugabyteClusterSpec) DeepCopy() *YugabyteClusterSpec {
	if in == nil {
		return nil
	}
	out := new(YugabyteClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *YugabyteClusterStatus) DeepCopyInto(out *YugabyteClusterStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new YugabyteClusterStatus.
func (in *YugabyteClusterStatus) DeepCopy() *YugabyteClusterStatus {
	if in == nil {
		return nil
	}
	out := new(YugabyteClusterStatus)
	in.DeepCopyInto(out)
	return out
}
