apiVersion: database.rook.crossplane.io/v1alpha1
kind: CockroachClusterClass
metadata:
  name: cockroach-standard
  annotations:
    resourceclass.crossplane.io/is-default-class: "true"
specTemplate:
  providerRef:
    name: demo-k8s-provider
  reclaimPolicy: Delete
  writeConnectionSecretsToNamespace: crossplane-system
  forProvider:
    name: my-test-cockroach
    namespace: rook-cockroachdb
    scope:
      nodeCount: 3
      volumeClaimTemplates:
      - metadata:
          name: rook-cockroachdb-data
        spec:
          accessModes: [ "ReadWriteOnce" ]
          resources:
            requests:
              storage: "1Gi"
    network:
      ports:
      - name: http
        port: 8080
      - name: grpc
        port: 26257
    secure: false
    cachePercent: 25
    maxSQLMemoryPercent: 25
