apiVersion: v1
kind: Namespace
metadata:
  name: app-project1-dev
---
apiVersion: database.crossplane.io/v1alpha1
kind: PostgreSQLInstanceClass
metadata:
  name: postgresql-standard
  namespace: app-project1-dev
classRef:
  kind: CockroachClusterClass
  apiVersion: database.rook.crossplane.io/v1alpha1
  name: cockroach-standard
  namespace: rook-infra-dev
---
apiVersion: database.rook.crossplane.io/v1alpha1
kind: CockroachClusterClass
metadata:
  name: cockroach-standard
  namespace: rook-infra-dev
specTemplate:
  providerRef:
    name: demo-k8s-provider
    namespace: rook-infra-dev
  reclaimPolicy: Delete
  forProvider:
    name: my-test-cockroach
    namespace: rook-cockroachdb
    scope:
      nodeCount: 3
      volumeClaimTemplates:
      - metadata:
          name: rook-cockroachdb-data
        spec:
          accessModes: [ "ReadWriteOnce" ]
          resources:
            requests:
              storage: "1Gi"
    network:
      ports:
      - name: http
        port: 8080
      - name: grpc
        port: 26257
    secure: false
    cachePercent: 25
    maxSQLMemoryPercent: 25
