apiVersion: database.rook.crossplane.io/v1alpha1
kind: CockroachCluster
metadata:
  name: test-cluster
  namespace: rook-infra-dev
spec:
  providerRef:
    name: demo-k8s-provider
    namespace: rook-infra-dev
  reclaimPolicy: Delete
  forProvider:
    name: my-test-cockroach
    namespace: rook-cockroachdb
    scope:
      nodeCount: 3
      volumeClaimTemplates:
        - spec:
            accessModes: [ "ReadWriteOnce" ]
            # Uncomment and specify your StorageClass, otherwise
            # the cluster admin defined default StorageClass will be used.
            #storageClassName: "my-storage-class"
            resources:
              requests:
                storage: "100Gi"
    network:
      ports:
      - name: http
        port: 8080
      - name: grpc
        port: 26257
    secure: false
    cachePercent: 25
    maxSQLMemoryPercent: 25
    # A key/value list of annotations
    annotations:
    #  key: value