
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: providers.gcp.crossplane.io
spec:
  additionalPrinterColumns:
  - JSONPath: .spec.projectID
    name: PROJECT-ID
    type: string
  - JSONPath: .metadata.creationTimestamp
    name: AGE
    type: date
  - JSONPath: .spec.credentialsSecretRef.name
    name: SECRET-NAME
    priority: 1
    type: string
  group: gcp.crossplane.io
  names:
    kind: Provider
    listKind: ProviderList
    plural: providers
    singular: provider
  scope: ""
  subresources: {}
  validation:
    openAPIV3Schema:
      description: A Provider configures a GCP 'provider', i.e. a connection to a
        particular GCP project using a particular GCP service account
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: A ProviderSpec defines the desired state of a Provider.
          properties:
            credentialsSecretRef:
              description: A Secret containing JSON encoded credentials for a Google
                Service Account that will be used to authenticate to this GCP Provider.
              properties:
                key:
                  description: The key of the secret to select from.  Must be a valid
                    secret key.
                  type: string
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
                optional:
                  description: Specify whether the Secret or it's key must be defined
                  type: boolean
              required:
              - key
              type: object
            projectID:
              description: ProjectID is the project name (not numerical ID) of this
                GCP Provider.
              type: string
          required:
          - credentialsSecretRef
          - projectID
          type: object
      type: object
  version: v1alpha2
  versions:
  - name: v1alpha2
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
